切换成2.6.0

diff --git a/scripts/extract-ikconfig b/scripts/extract-ikconfig
--- a/scripts/extract-ikconfig
+++ b/scripts/extract-ikconfig
@@ -1,67 +1,66 @@
-#!/bin/sh
-# ----------------------------------------------------------------------
-# extract-ikconfig - Extract the .config file from a kernel image
-#
-# This will only work when the kernel was compiled with CONFIG_IKCONFIG.
-#
-# The obscure use of the "tr" filter is to work around older versions of
-# "grep" that report the byte offset of the line instead of the pattern.
-#
-# (c) 2009,2010 Dick Streefland <dick@streefland.net>
-# Licensed under the terms of the GNU General Public License.
-# ----------------------------------------------------------------------
+#! /bin/bash 
+# extracts .config info from a [b]zImage file
+# uses: binoffset (new), dd, zcat, strings, grep
+# $arg1 is [b]zImage filename
 
-cf1='IKCFG_ST\037\213\010'
-cf2='0123456789'
+TMPFILE=""
 
-dump_config()
+usage()
 {
-	if	pos=`tr "$cf1\n$cf2" "\n$cf2=" < "$1" | grep -abo "^$cf2"`
+	echo "  usage: extract-ikconfig [b]zImage_filename"
+}
+
+clean_up()
+{
+	if [ -z $ISCOMP ]
 	then
-		pos=${pos%%:*}
-		tail -c+$(($pos+8)) "$1" | zcat > $tmp1 2> /dev/null
-		if	[ $? != 1 ]
-		then	# exit status must be 0 or 2 (trailing garbage warning)
-			cat $tmp1
-			exit 0
-		fi
+		rm -f $TMPFILE
 	fi
 }
 
-try_decompress()
-{
-	for	pos in `tr "$1\n$2" "\n$2=" < "$img" | grep -abo "^$2"`
-	do
-		pos=${pos%%:*}
-		tail -c+$pos "$img" | $3 > $tmp2 2> /dev/null
-		dump_config $tmp2
-	done
-}
-
-# Check invocation:
-me=${0##*/}
-img=$1
-if	[ $# -ne 1 -o ! -s "$img" ]
+if [ $# -lt 1 ]
 then
-	echo "Usage: $me <kernel-image>" >&2
-	exit 2
+	usage
+	exit
 fi
 
-# Prepare temp files:
-tmp1=/tmp/ikconfig$$.1
-tmp2=/tmp/ikconfig$$.2
-trap "rm -f $tmp1 $tmp2" 0
+image=$1
 
-# Initial attempt for uncompressed images or objects:
-dump_config "$img"
+# There are two gzip headers, as well as arches which don't compress their
+# kernel.
+GZHDR="0x1f 0x8b 0x08 0x00"
+if [ `binoffset $image $GZHDR >/dev/null 2>&1 ; echo $?` -ne 0 ]
+then
+	GZHDR="0x1f 0x8b 0x08 0x08"
+	if [ `binoffset $image $GZHDR >/dev/null 2>&1 ; echo $?` -ne 0 ]
+	then
+		ISCOMP=0
+	fi
+fi
 
-# That didn't work, so retry after decompression.
-try_decompress '\037\213\010' xy    gunzip
-try_decompress '\3757zXZ\000' abcde unxz
-try_decompress 'BZh'          xy    bunzip2
-try_decompress '\135\0\0\0'   xxx   unlzma
-try_decompress '\211\114\132' xy    'lzop -d'
+PID=$$
 
-# Bail out:
-echo "$me: Cannot find kernel config." >&2
-exit 1
+# Extract and uncompress the kernel image if necessary
+if [ -z $ISCOMP ]
+then
+	TMPFILE="/tmp/`basename $image`.vmlin.$PID"
+	dd if=$image bs=1 skip=`binoffset $image $GZHDR` 2> /dev/null | zcat > $TMPFILE
+else
+	TMPFILE=$image
+fi
+
+# Look for strings.
+strings $TMPFILE | grep "CONFIG_BEGIN=n" > /dev/null
+if [ $? -eq 0 ]
+then
+	strings $TMPFILE | awk "/CONFIG_BEGIN=n/,/CONFIG_END=n/" > $image.oldconfig.$PID
+else
+	echo "ERROR: Unable to extract kernel configuration information."
+	echo "       This kernel image may not have the config info."
+	clean_up
+	exit 1
+fi
+
+echo "Kernel configuration written to $image.oldconfig.$PID"
+clean_up
+exit 0
